Ang-0001: Message service begin
kaskoitra/Itransition2020ANG pull request #1
Opened 2020-08-25 11:18 UTC by kaskoitra

Ang-0001: A new message service has been added to handle messages.

2020-08-25 11:21 UTC, tihonk approved these changes

2020-08-25 13:41 UTC, Sapron12 requested changes

2020-08-25 13:41 UTC, Sapron12 commented on src/app/message.service.ts
> +  // tslint:disable-next-line:typedef variable-name
![image](https://user-images.githubusercontent.com/44747416/91181501-b10ac000-e6f1-11ea-948c-ac4524429f2d.png)

2020-08-25 15:51 UTC, kaskoitra commented on src/app/message.service.ts
> +  // tslint:disable-next-line:typedef variable-name
@Sapron12 Done

2020-09-02 07:53 UTC, Vlada0612 commented on src/app/app.component.html
> +<!--            <span class="badge badge-danger">11</span>-->
?

2020-09-02 07:55 UTC, Vlada0612 approved these changes

2020-09-02 11:14 UTC, Sapron12 approved these changes

2020-09-02 11:19 UTC, merged